### ISSUE TITLE
DNS Resolution

### ISSUE THREAD

**Issue by brimonk** [ruvolof/nc-for-android#1]
## Feature Request

I downloaded the application earlier today, just to test some networking I'm working on, and the application says that using a domain name is invalid syntax. Just as an example, this fails as a syntax error:

```sh
nc google.com 80
```

I'm not sure if you're maintaining the app, but this change would be super helpful, as I don't (usually) have computers on WiFi, just my phone.

**Comment by ruvolof** [comment]
Hello!

Thanks for the report! I wasn't actually maintaining this app. :D
Thanks for the report and interest in it. It wasn't an issue with DNS resolution, I was explicitly checking for an IP address for the host, I guess this was what I needed when I first coded this.

Later today I will try to push the new app version to the play store and let me know if this works for you when you receive the update.

Cheers
