### ISSUE TITLE
no known rule to make it error

### ISSUE THREAD

**Issue by mnaveedpaki** [ruvolof/nc-for-android#5]
ninja: error: '/Users/bbt/AndroidStudioProjects/NcatAndroid/app/src/main/cpp/libs/arm64-v8a/libncat.so', needed by '/Users/bbt/AndroidStudioProjects/NcatAndroid/app/build/intermediates/cxx/Debug/654h4j29/obj/arm64-v8a/do_nothing.so', missing and no known rule to make it

**Comment by ruvolof** [comment]
Hello,

Looks like you didn't compile the ncat executable, and you are right as I didn't specify anywhere that this should be compiled.

```
cd app/src/main/cpp
./make_ncat.sh
```

Unfortunately at the moment I don't have a script that would work on Windows.

Are you able to extract the executable from the apk after downloading it from the play store?

**Comment by ruvolof** [comment]
I just made a release with the ready APK.

If you are unable to compile ncat yourself, you can download the apk from the release page, unzip it and copy the `lib` folder in `app/src/main/cpp/`, and rename it `libs`. At the end you tree structure should look like this:

```
app/src/main/cpp/libs/
├── arm64-v8a
│   └── libncat.so
└── armeabi-v7a
    └── libncat.so
```
